export const SHOW_PROJECTS = 'SHOW_PROJECTS';
export const SHOW_EDUCATION = 'SHOW_EDUCATION';
export const SHOW_COMERCIAL = 'SHOW_COMERCIAL';
export const SHOW_VOLUNTEERING = 'SHOW_VOLUNTEERING';
export const SHOW_FEEDBACK = 'SHOW_FEEDBACK';
export const SHOW_HOBBIES = 'SHOW_HOBBIES';
export const SHOW_TECHNOLOGIES = 'SHOW_TECHNOLOGIES';

export const CHECK_HOBBIES = 'CHECK_HOBBIES';
export const CHECK_EXPERIENCE = 'CHECK_EXPERIENCE';
export const CHECK_FEEDBACK = 'CHECK_FEEDBACK';
export const CHECK_PROJECTS = 'CHECK_PROJECTS';